In [2]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a2 = a[np.newaxis]
a2

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [36]:
np.empty(4)

array([1.22710428e-311, 1.22707163e-311, 1.22707163e-311, 1.22707163e-311])

In [12]:
np.arange(3)

array([0, 1, 2])

In [13]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [14]:
np.linspace(0,10,num=3)

array([ 0.,  5., 10.])

In [15]:
np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
a.shape

(10,)

In [25]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[0 2 4 6 8]
