In [1]:
import numpy as np
#Creating sample array
arr = np.arange(0,11)
#Show
arr
#Get a value at an index
arr = np.arange(5,21)
arr[8]
arr[1:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [2]:
arr[:5]

array([5, 6, 7, 8, 9])

In [3]:
arr[1:5]

array([6, 7, 8, 9])

In [4]:
arr[0:11]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [7]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [8]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [9]:
import numpy as np

In [10]:
arr = np.arange(1,11)
arr
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [13]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr = np.arange(0,10)
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
#Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Users\USER\Ana\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [19]:
#Also warning, but not an error instead infinity
1/arr

C:\Users\USER\Ana\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [20]:
#Calculating exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [21]:
np.max(arr) #same as arr.max()

9

In [22]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [23]:
np.log(arr)

C:\Users\USER\Ana\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
import numpy as np

In [24]:
my_list = [1,2,3]
my_list
np.array(my_list)
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix
np.array(my_matrix)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [27]:
np.random.rand(2)

array([0.72831017, 0.56052207])

In [28]:
np.random.randn(2)

array([-0.31894436,  0.74884421])

In [29]:
np.random.randint(1,100,10)

array([36, 67, 86, 81, 36, 62,  8, 13, 36, 59])

In [31]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [32]:
ranarr

array([ 1, 49, 23, 12, 11,  6,  0, 41, 10, 11])

In [33]:
arr.shape

(25,)

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr.shape

(25,)

In [36]:
np.arange(0,25).reshape(5,5).shape

(5, 5)

In [37]:
ranarr.max()

49

In [38]:
ranarr.min()

0

In [39]:
ranarr.argmin()

6

In [40]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [41]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [42]:
arr.dtype

dtype('int32')

In [43]:
np.zeros(3)

array([0., 0., 0.])

In [44]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
np.full((5,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [50]:
np.ones((5,5))*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])